Pim\Bundle\BaseConnectorBundle\Reader\File\YamlReader:
    properties:
        filePath:
            - NotBlank:
                groups: [Execution]
            - Pim\Component\Catalog\Validator\Constraints\File:
                allowedExtensions: ["yml", "yaml"]
                groups: [Execution]
        uploadAllowed:
            - Type:
                type: "bool"
            - IsTrue:
                groups: [UploadExecution]
# TODO: add constraint class + drop this file