parameters:
    pim_import_export.form.type.job_instance.class:   Pim\Bundle\ImportExportBundle\Form\Type\JobInstanceType
    pim_import_export.form.type.job_parameters.class: Pim\Bundle\ImportExportBundle\Form\Type\JobParametersType

services:
    pim_import_export.form.type.job_instance:
        class: %pim_import_export.form.type.job_instance.class%
        arguments:
            - '@akeneo_batch.connectors'
            - '@translator'
        tags:
            - { name: form.type, alias: pim_import_export_job_instance }

    pim_import_export.form.type.job_parameters:
        class: %pim_import_export.form.type.job_parameters.class%
        tags:
            - { name: form.type, alias: pim_import_export_job_parameters }
