imports:
    - { resource: config_prod.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver: array
                query_cache_driver:    array
                result_cache_driver:   array

swiftmailer:
    disable_delivery: true

pim_enrich:
    record_mails: true

parameters:
    max_products_category_removal: 20
