pim_enrich_variant_group_index:
    path: /.{_format}
    defaults: { _controller: pim_enrich.controller.variant_group:indexAction, _format: html }
    requirements:
        _format: html|json

pim_enrich_variant_group_create:
    path: /create
    defaults: { _controller: pim_enrich.controller.variant_group:createAction }

pim_enrich_variant_group_edit:
    path: /{id}/edit
    defaults: { _controller: pim_enrich.controller.variant_group:editAction }
    requirements:
        id: \d+

pim_enrich_variant_group_remove_attribute_rest:
    path: /rest/{id}/{attributeId}
    defaults: { _controller: pim_enrich.controller.rest.variant_group_attribute:removeAttributeAction, _format: json }
    requirements:
        id: '[0-9a-f]+'
        attributeId: '\d+'
        _format: json
    methods: [DELETE]

pim_enrich_variant_group_rest_index:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.variant_group:indexAction, _format: json }
    methods: [GET]

pim_enrich_variant_group_rest_get:
    path: /rest/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.variant_group:getAction, _format: json }
    requirements:
        identifier: '[a-zA-Z0-9_]+'
    methods: [GET]

pim_enrich_variant_group_rest_post:
    path: /rest/{id}
    defaults: { _controller: pim_enrich.controller.rest.variant_group:postAction, _format: json }
    requirements:
        id: \d+
    methods: [POST]

pim_enrich_variant_group_rest_remove:
    path: /rest/{id}
    defaults: { _controller: pim_enrich.controller.rest.variant_group:removeAction }
    requirements:
        id: \d+
    methods: [DELETE]
