parameters:
    pim_enrich.view_element.attribute.tab.parameter.template: 'PimEnrichBundle:Attribute:Tab/parameter.html.twig'
    pim_enrich.view_element.attribute.tab.value.template:     'PimEnrichBundle:Attribute:Tab/value.html.twig'
    pim_enrich.view_element.attribute.tab.history.template:   'PimEnrichBundle:Form:Tab/history.html.twig'

services:
    ## Tabs
    pim_enrich.view_element.attribute.tab.parameter:
        parent: pim_enrich.view_element.base
        arguments:
            - 'pim_enrich.attribute.tab.parameter'
            - %pim_enrich.view_element.attribute.tab.parameter.template%
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_attribute_form.form_tab, position: 90 }

    pim_enrich.view_element.attribute.tab.value:
        parent: pim_enrich.view_element.base
        arguments:
            - 'pim_enrich.attribute.tab.value'
            - %pim_enrich.view_element.attribute.tab.value.template%
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_attribute_form.form_tab, position: 100 }

    pim_enrich.view_element.attribute.tab.history:
        parent: pim_enrich.view_element.base
        arguments:
            - 'pim_enrich.attribute.tab.history'
            - %pim_enrich.view_element.attribute.tab.history.template%
        calls:
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.edit_form'] ]
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_attribute_history'}] ]
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_attribute_form.form_tab, position: 110 }

    ## sub forms
    pim_enrich.view_element.attribute.general_parameters:
        class: '%pim_enrich.view_element.base.class%'
        arguments:
            - ''
            - 'PimEnrichBundle:Attribute:Tab/_default_parameter_form.html.twig'
            -
                allowed_form_types:
                    - code
                    - attributeType
                    - scopable
                    - reference_data_name
                    - localizable
                    - unique
                    - availableLocales
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_attribute_form.general_parameters, position: 90 }

    pim_enrich.view_element.attribute.backend_parameter:
        class: '%pim_enrich.view_element.base.class%'
        arguments:
            - ''
            - 'PimEnrichBundle:Attribute:Tab/_default_parameter_form.html.twig'
            -
                allowed_form_types:
                    - group
                    - useableAsGridFilter
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_attribute_form.backend_parameter, position: 90 }
