parameters:
    pim_connector.job_parameters.simple_csv_export.class: Pim\Component\Connector\Job\JobParameters\SimpleCsvExport

services:
    pim_connector.job_parameters.simple_csv_export:
        class: %pim_connector.job_parameters.simple_csv_export.class%
        arguments:
            -
                - 'pim_base_connector.jobs.csv_attribute_export.title'
                - 'pim_base_connector.jobs.csv_family_export.title'
                - 'pim_base_connector.jobs.csv_variant_group_export.title'
                - 'pim_base_connector.jobs.csv_group_export.title'
                - 'pim_base_connector.jobs.csv_association_type_export.title'
                - 'pim_base_connector.jobs.csv_attribute_option_export.title'
                - 'pim_base_connector.jobs.csv_category_export.title'
        tags:
            - { name: akeneo_batch.job_parameters.default }
