parameters:
    pim_connector.job_parameters.defaults.simple_csv_export.class:     Pim\Component\Connector\Job\JobParameters\Defaults\SimpleCsvExport
    pim_connector.job_parameters.defaults.product_csv_export.class:    Pim\Component\Connector\Job\JobParameters\Defaults\ProductCsvExport
    pim_connector.job_parameters.constraints.simple_csv_export.class:  Pim\Component\Connector\Job\JobParameters\Constraints\SimpleCsvExport
    pim_connector.job_parameters.constraints.product_csv_export.class: Pim\Component\Connector\Job\JobParameters\Constraints\ProductCsvExport

services:
    # Default parameters depending on Job
    pim_connector.job_parameters.defaults.simple_csv_export:
        class: %pim_connector.job_parameters.defaults.simple_csv_export.class%
        arguments:
            -
                - 'pim_base_connector.jobs.csv_attribute_export.title'
                - 'pim_base_connector.jobs.csv_family_export.title'
                - 'pim_base_connector.jobs.csv_variant_group_export.title'
                - 'pim_base_connector.jobs.csv_group_export.title'
                - 'pim_base_connector.jobs.csv_association_type_export.title'
                - 'pim_base_connector.jobs.csv_attribute_option_export.title'
                - 'pim_base_connector.jobs.csv_category_export.title'
        tags:
            - { name: akeneo_batch.job_parameters.defaults }

    pim_connector.job_parameters.defaults.product_csv_export:
        class: %pim_connector.job_parameters.defaults.product_csv_export.class%
        arguments:
            -
                - 'pim_base_connector.jobs.csv_product_export.title'
        tags:
            - { name: akeneo_batch.job_parameters.defaults }

    # Validation constraints depending on Job
    pim_connector.job_parameters.constraints.simple_csv_export:
        class: %pim_connector.job_parameters.constraints.simple_csv_export.class%
        arguments:
            -
                - 'pim_base_connector.jobs.csv_attribute_export.title'
                - 'pim_base_connector.jobs.csv_family_export.title'
                - 'pim_base_connector.jobs.csv_variant_group_export.title'
                - 'pim_base_connector.jobs.csv_group_export.title'
                - 'pim_base_connector.jobs.csv_association_type_export.title'
                - 'pim_base_connector.jobs.csv_attribute_option_export.title'
                - 'pim_base_connector.jobs.csv_category_export.title'
        tags:
            - { name: akeneo_batch.job_parameters.constraints }

    pim_connector.job_parameters.constraints.product_csv_export:
        class: %pim_connector.job_parameters.constraints.product_csv_export.class%
        arguments:
            - '@pim_connector.job_parameters.constraints.simple_csv_export'
            -
                - 'pim_base_connector.jobs.csv_product_export.title'
        tags:
            - { name: akeneo_batch.job_parameters.constraints }
