parameters:
    pim_connector.job_parameters.constraints.simple_mass_edit.class:     Pim\Bundle\EnrichBundle\Connector\Job\JobParameters\Constraints\SimpleMassEdit
    pim_connector.job_parameters.constraints.product_quick_export.class: Pim\Bundle\EnrichBundle\Connector\Job\JobParameters\Constraints\ProductQuickExport

services:
    pim_connector.job_parameters.constraints.simple_mass_edit:
        class: %pim_connector.job_parameters.constraints.simple_mass_edit.class%
        arguments:
            -
                - 'update_product_value'
                - 'add_product_value'
                - 'edit_common_attributes'
                - 'set_attribute_requirements'
                - 'add_to_variant_group'
        tags:
            - { name: akeneo_batch.job_parameters.constraints }

    pim_connector.job_parameters.constraints.product_csv_quick_export:
        class: %pim_connector.job_parameters.constraints.product_quick_export.class%
        arguments:
            - '@pim_connector.job_parameters.constraints.simple_csv_export'
            -
                - 'csv_product_quick_export'
        tags:
            - { name: akeneo_batch.job_parameters.constraints }

    pim_connector.job_parameters.constraints.product_xlsx_quick_export:
        class: %pim_connector.job_parameters.constraints.product_quick_export.class%
        arguments:
            - '@pim_connector.job_parameters.constraints.simple_xlsx_export'
            -
                - 'xlsx_product_quick_export'
        tags:
            - { name: akeneo_batch.job_parameters.constraints }
