parameters:
    akeneo_batch.job_factory.class:          Akeneo\Bundle\BatchBundle\Job\JobFactory
    akeneo_batch.step_factory.class:         Akeneo\Bundle\BatchBundle\Step\StepFactory
    akeneo_batch.job_instance_factory.class: Akeneo\Bundle\BatchBundle\Job\JobInstanceFactory

services:
    akeneo_batch.job_factory:
        class: %akeneo_batch.job_factory.class%
        arguments:
            - @event_dispatcher
            - @akeneo_batch.job_repository

    akeneo_batch.job_instance_factory:
        class: %akeneo_batch.job_instance_factory.class%
        arguments:
            - %akeneo_batch.entity.job_instance.class%

    akeneo_batch.step_factory:
        class: %akeneo_batch.step_factory.class%
        arguments:
            - @event_dispatcher
            - @akeneo_batch.job_repository
