parameters:
    akeneo_storage_utils.updater.base.class: Akeneo\Component\Batch\Updater\JobInstanceUpdater

services:
    akeneo_batch.updater.job_instance:
        class: %akeneo_storage_utils.updater.base.class%
        arguments:
            - '@akeneo_batch.job_parameters_factory'
            # TODO: circular reference, this registry needs to be re-worked, the way we register Jobs in DI too ...
            - '@service_container'
