language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "hhvm"

# Allow to use container infrastructure
sudo: false

before_script:
  - composer self-update
  - composer update

script: ./bin/phpspec run spec/
